# Generated by Django 3.1 on 2020-09-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200901_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userValidRegister',
        ),
    ]
